[connections.supabase]
SUPABASE_URL = "https://awfaifhwntypvbiyxfqs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZmFpZmh3bnR5cHZiaXl4ZnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTMyMzgsImV4cCI6MjA2MTIyOTIzOH0.X3fS6pMUkCzpREfndDXj5qnDUsfIR1CMWZ_kkZpgxqc"